### ISSUE TITLE
Class Not found exception: percipioglobal\colourswatches\fields\ColourSwatches while creating new field.

### ISSUE THREAD

**Issue by TomHell** [percipioglobal/craft-colour-swatches#112]
Creating a new field of type "Color Swatches" ends up in Class Not Found exception.
Same occurs when running craft `utils/fix-field-layout-uids` command.

- PHP 8.1
- Craft CMS 4.4.16.1
- Colour Swatches 4.3.0

Exception Stack Trace
`2023-08-22T07:14:09+00:00 [ERROR][] Error: Class "percipioglobal\colourswatches\fields\ColourSwatches" not found in /vendor/craftcms/cms/src/services/Fields.php:1648`
```
#0 /vendor/craftcms/cms/src/services/Matrix.php(312): craft\services\Fields->applyFieldSave('0c6b0735-02df-4...', Array, 'matrixBlockType...') 
#1 /vendor/craftcms/cms/src/base/ApplicationTrait.php(1781): craft\services\Matrix->handleChangedBlockType(Object(craft\events\ConfigEvent)) 
#2 /vendor/craftcms/cms/src/services/ProjectConfig.php(1126): craft\console\Application->craft\base\{closure}(Object(craft\events\ConfigEvent)) #3 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent)) 
#4 /vendor/yiisoft/yii2/base/Component.php(633): call_user_func(Array, Object(craft\events\ConfigEvent)) 
#5 /vendor/craftcms/cms/src/models/ProjectConfigData.php(82): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent)) 
#6 /vendor/craftcms/cms/src/services/ProjectConfig.php(516): craft\models\ProjectConfigData->commitChanges(Array, Array, 'matrixBlockType...', true, NULL, true) 
#7 /vendor/craftcms/cms/src/services/ProjectConfig.php(476): craft\services\ProjectConfig->_setInternal('matrixBlockType...', Array, NULL, true, false) 
#8 /vendor/craftcms/cms/src/console/controllers/utils/FixFieldLayoutUidsController.php(70): craft\services\ProjectConfig->set('matrixBlockType...', Array) 
#9 /vendor/craftcms/cms/src/console/controllers/utils/FixFieldLayoutUidsController.php(78): craft\console\controllers\utils\FixFieldLayoutUidsController->_fixUids(Array, 553, 'matrixBlockType...', Array) 
#10 /vendor/craftcms/cms/src/console/controllers/utils/FixFieldLayoutUidsController.php(78): craft\console\controllers\utils\FixFieldLayoutUidsController->_fixUids(Array, 553, 'matrixBlockType...', Array) 
#11 /vendor/craftcms/cms/src/console/controllers/utils/FixFieldLayoutUidsController.php(33): craft\console\controllers\utils\FixFieldLayoutUidsController->_fixUids(Array, 553) 
#12 [internal function]: craft\console\controllers\utils\FixFieldLayoutUidsController->actionIndex() 
#13 /vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) 
#14 /vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array) 
#15 /vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('', Array) 
#16 /vendor/craftcms/cms/src/console/ControllerTrait.php(87): yii\console\Controller->runAction('', Array) 
#17 /vendor/craftcms/cms/src/console/Controller.php(217): craft\console\Controller->traitRunAction('', Array) 
#18 /vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction('', Array) 
#19 /vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('utils/fix-field...', Array) 
#20 /vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction('utils/fix-field...', Array) #21 /vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('utils/fix-field...', Array) #22 /vendor/craftcms/cms/src/console/Application.php(121): yii\console\Application->handleRequest(Object(craft\console\Request)) 
#23 /vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request)) 
#24 /craft(22): yii\base\Application->run() #25 {main} {"memory":49659448,"exception":"[object] (Error(code: 0): Class \"percipioglobal\\colourswatches\\fields\\ColourSwatches\" not found at /vendor/craftcms/cms/src/services/Fields.php:1648)"} {"yii_category":"Error"}
```

**Comment by eirabben** [comment]
I had the same problem after updating to Craft 4. It seems that the namespace for the plugin has changed from `percipioglobal\colourswatches\fields\ColourSwatches` to `percipiolondon\colourswatches\fields\ColourSwatches`. 

Resaving all color fields, as well as matrix blocks containing color fields fixed the issue for me.

Maybe it would be possible to have a migration that does this when updating the plugin?

**Comment by maxfenton** [comment]
Thanks for this ticket. I had the same issue and solved it by re-saving the one ColourSwatches field, which updated the yaml like so:
![Screenshot 2024-03-25 at 12 54 37 PM](https://github.com/craftpulse/craft-colour-swatches/assets/906502/4d50b28b-75f3-4340-a8cb-6131b123002c)

**Comment by cookie10codes** [comment]
Wrote a new migration for this issue @TomHell
